import {
  BinzipImage,
  CoffeezipImage,
  FutbolistaImage,
  KokkokCarImage,
  KokkokImage,
  KokkokMoveImage,
  LSMImage,
  MolbwaImage,
  PortfolioImage,
} from "@/assets";
import type { ProjectDetail, ProjectItem } from "@/types";

export const PROJECT_DATA: ProjectItem[] = [
  {
    description: "라오스 종합 생활 서비스 KOKKOK의 관리자 웹 페이지",
    image: KokkokImage,
    skills: ["React", "Typescipt"],
    tag: "team",
    title: "KOKKOK Admin",
  },
  {
    description: "라오스 여객 운송 서비스 KOKKOK Move의 관리자 웹 페이지",
    image: KokkokMoveImage,
    skills: ["React", "Typescipt"],
    tag: "team",
    title: "KOKKOK Move Admin",
  },
  {
    description: "라오스 신차·중고차 판매 서비스 KOKKOK Car의 관리자 웹 페이지",
    image: KokkokCarImage,
    skills: ["React", "Typescipt"],
    tag: "team",
    title: "KOKKOK Car Admin",
  },
  {
    description:
      "라오스 모빌리티 기업 Lao Smart Mobility의 기업 및 주요 서비스를 소개하는 반응형 웹사이트",
    image: LSMImage,
    skills: ["Next", "Typescript"],
    tag: "team",
    title: "LSM Landing",
  },
  {
    description: "최호진의 개인 포트폴리오 페이지",
    image: PortfolioImage,
    skills: ["React", "Framer Motion"],
    tag: "personal",
    title: "CHJ's Portfolio",
  },
  {
    description:
      "서울의 늦은 밤, 아직 열려 있는 카페를 한눈에 찾을 수 있는 야간 카페 지도 서비스",
    image: CoffeezipImage,
    skills: ["React", "Kakao Map API"],
    tag: "team",
    title: "카페 찾는 부엉이",
  },
  {
    description:
      "보고 싶은 영화·드라마의 결말까지, 유튜브 몰아보기 영상을 한곳에서 빠르게 찾을 수 있는 서비스",
    image: BinzipImage,
    skills: ["Next", "Tailwind CSS"],
    tag: "personal",
    title: "Bin.Zip",
  },
  {
    description:
      "보고 싶은 영화·드라마의 결말까지, 유튜브 몰아보기 영상을 한곳에서 빠르게 찾을 수 있는 서비스",
    image: MolbwaImage,
    skills: ["React", "Styled-Components"],
    tag: "personal",
    title: "몰봐?!",
  },
  {
    description:
      "내 발에 맞는 축구화를 쉽고 빠르게 찾을 수 있는 맞춤형 축구화 추천 서비스",
    image: FutbolistaImage,
    skills: ["React", "Flask", "MySQL"],
    tag: "personal",
    title: "Futbolista",
  },
];

export const PROJECT_DETAIL: ProjectDetail[] = [
  {
    description:
      "라오스 종합 생활 서비스 KOKKOK의 React 기반 다국어 관리자 웹 백오피스 개발 및 마트 상품·쿠폰·멤버십·공지사항 등 서비스 운영 기능 구현",
    image: KokkokImage,
    skills: [
      "Vite",
      "React",
      "Typescript",
      "TanStack Query",
      "Zustand",
      "Emotion",
      "Turborepo",
      "Google Maps API",
      "React Hook Form",
      "Zod",
      "i18n",
      "MSW",
      "Vitest",
      "Storybook",
      "Eslint",
    ],
    tag: "team",
    title: "KOKKOK Admin",
    details: [
      "주문·배송 기사·차량 배정 및 지도 기반 배송 경로를 관리하는 배차 기능 개발",
      "주문 데이터 처리 로직을 Map 기반으로 개선하여 시간 복잡도를 O(n²)에서 O(n)으로 최적화",
      "MSW를 도입해 백엔드 API 개발 완료 이전부터 기능 테스트가 가능한 환경을 구축하고 API 연동 문제를 사전 발견·개선",
      "IA, 서비스 플로우차트 및 화면 설계서 작성 등 신규 서비스 기획 및 설계 참여",
      "디자인팀과 협의하여 공통 컴포넌트를 Storybook으로 관리하고 기능 및 사용 기준 문서화",
      "Turborepo 기반 모노레포 환경에서 서비스 및 공통 코드 관리",
      "Vitest를 활용해 기존 로직의 테스트 코드를 작성하고 테스트 과정에서 발견한 코드 문제 개선",
      "TanStack Query를 활용한 서버 상태 관리 및 API 기반 CRUD 기능 개발",
      "React Hook Form과 Zod를 활용한 폼 상태 관리 및 입력 데이터 검증",
      "i18n 기반 다국어 환경 구축 및 번역 문구 관리",
    ],
    github_url: "",
    demo_url: "",
  },
  {
    description:
      "라오스 승객과 운전자를 연결하는 여객 운송 서비스 KOKKOK Move의 React 기반 다국어 관리자 웹 백오피스 리뉴얼 및 운행 차량·운전자 등록·관리, 광고·공지사항 등 서비스 운영 기능 구현",
    image: KokkokMoveImage,
    skills: [
      "Vite",
      "React",
      "Typescript",
      "TanStack Query",
      "Zustand",
      "Emotion",
      "Turborepo",
      "Google Maps API",
      "React Hook Form",
      "Yup",
      "i18n",
      "Eslint",
    ],
    tag: "team",
    title: "KOKKOK Move Admin",
    details: [
      "Google Maps Marker Clustering을 도입해 차량 마커 렌더링 시간을 10초 이상에서 약 1초로 단축",
      "Google Places API 마이그레이션을 통해 기존 라이브러리의 지원 종료에 따른 서비스 영향 방지",
      "기존 관리자 백오피스를 리뉴얼하여 차량·운전자 관리 및 배차 운영 기능 개발",
      "TanStack Query를 활용한 서버 상태 관리 및 API 기반 CRUD 기능 개발",
      "Zustand를 활용한 전역 상태 관리",
      "React Hook Form과 Yup을 활용한 폼 상태 관리 및 입력 데이터 검증",
      "ESLint와 Perfectionist를 활용해 코드 작성 및 Props 정렬 규칙을 표준화",
      "Turborepo 기반 모노레포 환경에서 서비스 및 공통 코드 관리",
      "i18n 기반 다국어 환경 구축 및 언어별 콘텐츠 관리",
    ],
    github_url: "",
    demo_url: "",
  },
  {
    description:
      "라오스 신차·중고차 판매 서비스 KOKKOK Car의 React 기반 다국어 관리자 웹 백오피스 개발, 차량 등록·관리·광고·공지사항 등 서비스 운영 기능 구현",
    image: KokkokCarImage,
    skills: [
      "Vite",
      "React",
      "Typescript",
      "TanStack Query",
      "Zustand",
      "Emotion",
      "Turborepo",
      "Google Maps API",
      "React Hook Form",
      "Yup",
      "i18n",
      "Eslint",
    ],
    tag: "team",
    title: "KOKKOK Car Admin",
    details: [
      "Figma 디자인 가이드를 기반으로 차량 등록·관리, 광고, 공지사항 등 관리자 기능 개발",
      "TanStack Query를 활용한 서버 상태 관리 및 API 기반 CRUD 기능 개발",
      "React Hook Form과 Yup을 활용한 폼 상태 관리 및 입력 데이터 검증",
      "백엔드 팀과 협업하여 REST API Key 설정 및 API 연동",
      "i18n 기반 다국어 환경 구축 및 번역 문구 관리",
      "Turborepo 기반 모노레포 환경에서 서비스 및 공통 코드 관리",
      "Git 코드 리뷰 및 QC를 통한 기능·UI 개선",
    ],
    github_url: "",
    demo_url: "",
  },
  {
    description:
      "라오스 모빌리티 기업 Lao Smart Mobility의 기업 가치와 비전, 주요 서비스를 소개하는 Next 기반 반응형 웹사이트 개발",
    image: LSMImage,
    skills: ["Next", "Typescript", "Styled-Components", "i18n"],
    tag: "team",
    title: "LSM Landing",
    details: [
      "기존 랜딩 페이지를 리뉴얼하고 신규 페이지를 개발하여 기업 및 서비스 소개 콘텐츠 구축",
      "SEO 설정 및 검색 엔진 최적화를 통한 검색 노출 환경 개선",
      "사용자 디바이스에 따른 딥링크 이동 기능 구현",
      "i18n을 활용한 다국어 페이지 구성 및 언어별 콘텐츠 관리",
      "다양한 디바이스 환경을 고려한 반응형 웹 UI 구현",
      "서비스 약관 페이지 신규 제작 및 기존 페이지 수정",
    ],
    github_url: "",
    demo_url: "https://www.laosmartmobility.com/",
  },
  {
    description: "프론트엔드 개발자 최호진을 소개하는 개인 포트폴리오",
    image: PortfolioImage,
    skills: [
      "Vite",
      "React",
      "Typescript",
      "TanStack Query",
      "Styled-Components",
      "Zustand",
      "Swiper",
      "Framer",
      "Vercel",
      "Supabase",
    ],
    tag: "personal",
    title: "CHJ's Portfolio",
    details: [
      "React와 TypeScript를 기반으로 재사용 가능한 UI 컴포넌트 설계 및 구현",
      "Supabase Database와 Storage를 활용한 프로젝트 데이터 및 이미지 관리",
      "Zustand를 활용한 프로젝트 및 UI 상태 관리",
      "Swiper를 활용한 반응형 프로젝트 Carousel 구현",
      "Framer Motion을 활용한 UI 전환 및 인터랙션 애니메이션 구현",
      "GitHub와 Vercel을 연동한 CI/CD 기반 자동 배포 환경 구축",
    ],
    github_url: "https://github.com/Jack42chj/react-pf",
    demo_url: "https://choihojin.vercel.app/",
  },
  {
    description:
      "서울의 늦은 밤, 아직 열려 있는 카페를 한눈에 찾을 수 있는 야간 카페 지도 서비스",
    image: CoffeezipImage,
    skills: [
      "Vite",
      "React",
      "Kakao Map API",
      "Typescript",
      "Zustand",
      "Styled-Components",
      "TanStack Query",
      "Vercel",
      "Supabase",
    ],
    tag: "team",
    title: "카페 찾는 부엉이",
    details: [
      "React와 TypeScript를 기반으로 재사용 가능한 UI 컴포넌트 설계 및 구현",
      "Supabase를 활용한 데이터베이스 및 서비스 데이터 관리",
      "Supabase PostGIS를 활용한 위치 기반 카페 검색 기능 구현",
      "Kakao Map API를 활용한 카페 위치 및 지도 서비스 구현",
      "PWA를 적용한 모바일 디바이스 환경 지원",
      "GitHub Actions와 Vercel을 연동한 CI/CD 기반 자동 배포 환경 구축",
      "Google Analytics를 활용한 사용자 행동 및 서비스 지표 분석",
    ],
    github_url: "https://github.com/Jack42chj/coffe-zip",
    demo_url: "https://coffeezip.vercel.app/",
  },
  {
    description:
      "보고 싶은 영화·드라마의 결말까지, 유튜브 몰아보기 영상을 한곳에서 빠르게 찾을 수 있는 서비스",
    image: BinzipImage,
    skills: [
      "Next",
      "Typescript",
      "Zustand",
      "Tailwind CSS",
      "TanStack Query",
      "Vercel",
      "Supabase",
    ],
    tag: "personal",
    title: "Bin.Zip",
    details: [
      "Next.js와 TypeScript를 기반으로 재사용 가능한 UI 컴포넌트 설계 및 구현",
      "Supabase를 활용한 데이터베이스 및 서비스 데이터 관리",
      "Supabase Auth와 OAuth 2.0을 활용한 Google 소셜 로그인 구현",
      "Tailwind CSS를 활용한 반응형 UI 스타일링",
      "GitHub Actions와 Vercel을 연동한 CI/CD 기반 자동 배포 환경 구축",
    ],
    github_url: "https://github.com/Jack42chj/binzip-next",
    demo_url: "https://binzip.vercel.app/main",
  },
  {
    description:
      "보고 싶은 영화·드라마의 결말까지, 유튜브 몰아보기 영상을 한곳에서 빠르게 찾을 수 있는 서비스",
    image: MolbwaImage,
    skills: [
      "Vite",
      "React",
      "Typescript",
      "Zustand",
      "Styled-Components",
      "TanStack Query",
      "Vercel",
      "Supabase",
    ],
    tag: "personal",
    title: "몰봐?!",
    details: [
      "React와 TypeScript를 기반으로 재사용 가능한 UI 컴포넌트 설계 및 구현",
      "Supabase를 활용한 데이터베이스 및 서비스 데이터 관리",
      "Supabase Auth와 OAuth 2.0을 활용한 Google 소셜 로그인 구현",
      "Zustand를 활용한 사용자 인증 상태 및 로그인 정보 관리",
      "GitHub Actions와 Vercel을 연동한 CI/CD 기반 자동 배포 환경 구축",
    ],
    github_url: "https://github.com/Jack42chj/molbwa",
    demo_url: "https://molbwa.vercel.app/",
  },
  {
    description:
      "사용자의 발 정보를 기반으로 최적의 축구화를 추천하는 맞춤형 축구화 추천 서비스",
    image: FutbolistaImage,
    skills: [
      "Vite",
      "React",
      "TypeScript",
      "Material UI",
      "Redux",
      "Flask",
      "K-means++ Clustering",
      "Decision Tree",
      "MySQL",
    ],
    tag: "team",
    title: "Futbolista",
    details: [
      "React와 TypeScript를 기반으로 재사용 가능한 UI 컴포넌트 설계 및 구현",
      "Redux를 활용한 전역 상태 관리 및 사용자 데이터 관리",
      "Flask 기반 REST API 서버 구축 및 머신러닝 모델 연동",
      "MySQL을 활용한 축구화 데이터베이스 설계 및 구축",
      "MUI를 활용한 UI 컴포넌트 및 반응형 인터페이스 구현",
      "K-means++ 클러스터링 알고리즘을 활용한 축구화 특성별 군집화",
      "Decision Tree를 활용한 사용자 맞춤형 축구화 추천 모델 구현",
    ],
    github_url: "https://github.com/Jack42chj/molbwa",
    demo_url: "",
  },
];
